name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github @octokit/core

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          const { Octokit } = require("@octokit/core");
          const octokit = new Octokit({ auth: process.env.PERSONAL_ACCESS_TOKEN });

          async function getLanguages() {
            const repos = await octokit.request('GET /user/repos', {
              type: 'private',
              per_page: 100
            });

            let languageData = {};
            for (const repo of repos.data) {
              const languages = await octokit.request(`GET /repos/${repo.full_name}/languages`);
              for (const [language, bytes] of Object.entries(languages.data)) {
                if (!languageData[language]) {
                  languageData[language] = 0;
                }
                languageData[language] += bytes;
              }
            }
            return languageData;
          }

          async function updateReadme(languageData) {
            const fs = require('fs');
            let readme = fs.readFileSync('README.md', 'utf8');

            let languageStats = '### 💻 Most Used Languages\n\n';
            for (const [language, bytes] of Object.entries(languageData)) {
              languageStats += `- ${language}: ${bytes} bytes\n`;
            }

            readme = readme.replace(/### 💻 Most Used Languages[\s\S]*### 📫 How to Reach Me/, languageStats);
            fs.writeFileSync('README.md', readme);

            await octokit.request('PUT /repos/{owner}/{repo}/contents/{path}', {
              owner: 'luizmaiaj',
              repo: 'luizmaiaj',
              path: 'README.md',
              message: 'Update README with language stats',
              content: Buffer.from(readme).toString('base64'),
              branch: 'main'
            });
          }

          getLanguages().then(updateReadme);
